spring:
  application:
    name: service-a

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: service-a
            client-secret: cZ5Rb3UWpsb7Hm0BfnYmg5EWrJVDA2rc
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: http://keycloak/auth/realms/demo/protocol/openid-connect/token

  otel:
    exporter:
      otlp:
        endpoint: http://lgtm-loki-gateway.observability.svc.cluster.local:4318/v1/traces
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
  tracing:
    sampling:
      probability: 1.0 # 100% sampling for development

  otlp:
    metrics:
      export:
        url: http://lgtm-loki-gateway.observability.svc.cluster.local:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://lgtm-loki-gateway.observability.svc.cluster.local:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://lgtm-loki-gateway.observability.svc.cluster.local:4318/v1/logs

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

service:
  name: "Service B"
  description: "Demo service"
  version: "0.0.1"